sudo: false
before_cache:
- find . -name "*.py[co]" -print -delete
- rm -fv $HOME/.ivy2/pants/*.{css,properties,xml,xsl}
- rm -rf $HOME/.cache/pants/stats
cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.ivy2/pants"
  - "$HOME/opt"
language: python
python:
- '2.7'
env:
  global:
  - JAVA_HOME="$HOME/opt/jdk1.8.0_40"
  - JAVA_BIN="$HOME/opt/jdk1.8.0_40/bin/java"
  matrix:
  - COMMAND="./pants run src/java/org/suls/pants:app"
  - COMMAND="./pants bundle src/java/org/suls/pants:app && $JAVA_BIN -jar dist/src.java.org.suls.pants.app-bundle/main.jar"
  - COMMAND="./pants bundle src/java/org/suls/pants:app --bundle-jvm-deployjar && $JAVA_BIN -jar dist/src.java.org.suls.pants.app-bundle/main.jar"
before_script: |
  if ! "$HOME"/opt/jdk1.8.0_40/bin/java -version; then
    mkdir -p ~/opt
    wget --no-cookies --no-check-certificate --header \
      "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" \
      "http://download.oracle.com/otn-pub/java/jdk/8u40-b25/jdk-8u40-linux-x64.tar.gz"
    tar xzf jdk-8u40-linux-x64.tar.gz -C ~/opt
  fi
script: |
  uname -a
  git diff --exit-code || exit "$?"
  eval $COMMAND
